// flow-typed signature: 394ef8f9b42eec4a8e037255ee801d55
// flow-typed version: <<STUB>>/gl-mat4_v^1.1.4/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gl-mat4'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gl-mat4' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gl-mat4/adjoint' {
  declare module.exports: any;
}

declare module 'gl-mat4/clone' {
  declare module.exports: any;
}

declare module 'gl-mat4/copy' {
  declare module.exports: any;
}

declare module 'gl-mat4/create' {
  declare module.exports: any;
}

declare module 'gl-mat4/determinant' {
  declare module.exports: any;
}

declare module 'gl-mat4/fromQuat' {
  declare module.exports: any;
}

declare module 'gl-mat4/fromRotationTranslation' {
  declare module.exports: any;
}

declare module 'gl-mat4/frustum' {
  declare module.exports: any;
}

declare module 'gl-mat4/identity' {
  declare module.exports: any;
}

declare module 'gl-mat4/invert' {
  declare module.exports: any;
}

declare module 'gl-mat4/lookAt' {
  declare module.exports: any;
}

declare module 'gl-mat4/multiply' {
  declare module.exports: any;
}

declare module 'gl-mat4/ortho' {
  declare module.exports: any;
}

declare module 'gl-mat4/perspective' {
  declare module.exports: any;
}

declare module 'gl-mat4/perspectiveFromFieldOfView' {
  declare module.exports: any;
}

declare module 'gl-mat4/rotate' {
  declare module.exports: any;
}

declare module 'gl-mat4/rotateX' {
  declare module.exports: any;
}

declare module 'gl-mat4/rotateY' {
  declare module.exports: any;
}

declare module 'gl-mat4/rotateZ' {
  declare module.exports: any;
}

declare module 'gl-mat4/scale' {
  declare module.exports: any;
}

declare module 'gl-mat4/str' {
  declare module.exports: any;
}

declare module 'gl-mat4/translate' {
  declare module.exports: any;
}

declare module 'gl-mat4/transpose' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gl-mat4/adjoint.js' {
  declare module.exports: $Exports<'gl-mat4/adjoint'>;
}
declare module 'gl-mat4/clone.js' {
  declare module.exports: $Exports<'gl-mat4/clone'>;
}
declare module 'gl-mat4/copy.js' {
  declare module.exports: $Exports<'gl-mat4/copy'>;
}
declare module 'gl-mat4/create.js' {
  declare module.exports: $Exports<'gl-mat4/create'>;
}
declare module 'gl-mat4/determinant.js' {
  declare module.exports: $Exports<'gl-mat4/determinant'>;
}
declare module 'gl-mat4/fromQuat.js' {
  declare module.exports: $Exports<'gl-mat4/fromQuat'>;
}
declare module 'gl-mat4/fromRotationTranslation.js' {
  declare module.exports: $Exports<'gl-mat4/fromRotationTranslation'>;
}
declare module 'gl-mat4/frustum.js' {
  declare module.exports: $Exports<'gl-mat4/frustum'>;
}
declare module 'gl-mat4/identity.js' {
  declare module.exports: $Exports<'gl-mat4/identity'>;
}
declare module 'gl-mat4/index' {
  declare module.exports: $Exports<'gl-mat4'>;
}
declare module 'gl-mat4/index.js' {
  declare module.exports: $Exports<'gl-mat4'>;
}
declare module 'gl-mat4/invert.js' {
  declare module.exports: $Exports<'gl-mat4/invert'>;
}
declare module 'gl-mat4/lookAt.js' {
  declare module.exports: $Exports<'gl-mat4/lookAt'>;
}
declare module 'gl-mat4/multiply.js' {
  declare module.exports: $Exports<'gl-mat4/multiply'>;
}
declare module 'gl-mat4/ortho.js' {
  declare module.exports: $Exports<'gl-mat4/ortho'>;
}
declare module 'gl-mat4/perspective.js' {
  declare module.exports: $Exports<'gl-mat4/perspective'>;
}
declare module 'gl-mat4/perspectiveFromFieldOfView.js' {
  declare module.exports: $Exports<'gl-mat4/perspectiveFromFieldOfView'>;
}
declare module 'gl-mat4/rotate.js' {
  declare module.exports: $Exports<'gl-mat4/rotate'>;
}
declare module 'gl-mat4/rotateX.js' {
  declare module.exports: $Exports<'gl-mat4/rotateX'>;
}
declare module 'gl-mat4/rotateY.js' {
  declare module.exports: $Exports<'gl-mat4/rotateY'>;
}
declare module 'gl-mat4/rotateZ.js' {
  declare module.exports: $Exports<'gl-mat4/rotateZ'>;
}
declare module 'gl-mat4/scale.js' {
  declare module.exports: $Exports<'gl-mat4/scale'>;
}
declare module 'gl-mat4/str.js' {
  declare module.exports: $Exports<'gl-mat4/str'>;
}
declare module 'gl-mat4/translate.js' {
  declare module.exports: $Exports<'gl-mat4/translate'>;
}
declare module 'gl-mat4/transpose.js' {
  declare module.exports: $Exports<'gl-mat4/transpose'>;
}
